version: "3"
services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
  app:
    build: .
    command: /bin/bash -c "python -v main.py"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
volumes:
  db_data: {}
