# Generated by Django 4.1 on 2023-11-29 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("spqrapp", "0003_activity_activityhabit_activityrewards_channel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="server",
            name="admins",
        ),
        migrations.AddField(
            model_name="server",
            name="admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_servers",
                to="spqrapp.user",
            ),
        ),
        migrations.AlterField(
            model_name="pillar",
            name="color",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="role",
            name="color",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="role",
            name="level_to_reach_it",
            field=models.IntegerField(),
        ),
    ]
