# Generated by Django 4.2.3 on 2023-07-16 15:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("spqrapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="activitylog",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="session",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="nick",
            field=models.CharField(default="no nick", max_length=255),
        ),
    ]
